### PR TITLE
implement dropZeroColumns

### LINKED ISSUE #36: diff abund: what to do with lonely pointIds?
Sometimes we return data with lonely point ids. For example

```
	{
		"log2foldChange": -0.400749966260428,
		"pValue": 0.94041409168074,
		"adjustedPValue": 0.993844417394403,
		"pointID": "EUPATH_0000813.EUPATH_0009257_Bacteria_Firmicutes_Clostridia_Oscillospirales_UCG_010_"
	},
	{
		"pointID": "EUPATH_0000813.EUPATH_0009257_Bacteria_Firmicutes_Bacilli_Lactobacillales_Lactobacillaceae_Lactobacillus_Lactobacillus_delbrueckii"
	},
```

Are these taxa that failed the diff abund test? Is something else going wrong? Should we keep them or dump them?

### PR DESCRIPTION
**Pull request by asizemore**
Resolves #36 and requires https://github.com/VEuPathDB/veupathUtils/pull/17

Still in draft mode because of test failures. Update: tests all working as expected now!

Are there other computations we should add this behavior to as well? Beta div makes sense i'd think. Otherwise it shouldn't matter if there are 0 cols.

This PR only has the computation drop the columns and internally saves the dropped columns. Currently the droppedColumns are not going to the metadata endpoint or anything. That will be updated in a later PR. This PR fixes the error though and allows us to continue with development.

### CODE REVIEW

**Comment by asizemore** [comment]
@d-callan this PR and it's pair in veupathUtils are ready when you are!

**Comment by d-callan** [comment]
what is the plan for making these columns known to the client? if we want to add it to the metadata endpoint, that would i think require updating the VariableMapping in edacommon which im not sure makes sense? another option is to pass it as part of the stats endpoint, which i think only requires work here?

beta div doesnt actually require us to drop columns does it?

also im going to wait to actually review this until we talk about the utils pr.

**Comment by asizemore** [comment]
My plan was to update the metadata endpoint, because it felt more natural to me to look to 'metadata' for this info and to 'stats' for only numeric things. Right now 'metadata' returns only metadata on computed variables, but the dropped columns are like metadata about the whole computation. So i was thinking we'd put the dropped taxa there and similarly the number of samples actually used in the compute there as well. Even eventually when we send the compute logs (`ComputeResult@computationDetails`) it could go in the same spot.

Anyways, right we need to decide where this type of info belongs. Adding it to the stats endpoint would definitely be easier, but i'm not convinced yet that if i were to go looking for this info i would think to look to 'stats' instead of 'metadata'.

**Comment by asizemore** [comment]
Also thanks to purrr::discard basically all of that veupathUtils PR is unnecessary :) 
I'll update this one and then i can close the other!

**Comment by asizemore** [comment]
Code updated to use `purrr::discard`! Ready for your review!

Upon approval i'll close the veupathUtils PR.

**Comment by d-callan** [comment]
I'd like @ryanrdoherty thoughts about how to tell the client about cols we had to drop

**Comment by ryanrdoherty** [comment]
> I'd like @ryanrdoherty thoughts about how to tell the client about cols we had to drop

Based on my (possibly limited) understanding of all the comments above, I think this should go in stats, and then you can decide how to incorporate into the data plugin response.  "metadata" and "stats" might not be the right names for what those two endpoints are intended to do:

- "metadata" should probably be "computed-var-metadata" since that's the only thing it's really for
- "stats" should maybe be "non-computed-var-output", meaning any information that is not computed vars or their metadata

**Comment by asizemore** [comment]
Thanks @ryanrdoherty !

@d-callan  i'll move the droppedColumns to live under "stats" and reach out when it's ready for review again

**Comment by asizemore** [comment]
@d-callan ready for your reveiw!
i originally thought i should put the droppedColumns in the statistics slot now, but then i realized that will require api changes. We're not ready to use these values yet (we're not sure where to log them or how) so it seems like just getting this first step of dropping the columns and keeping track of who we've dropped is a positive feature wihtout scope creeping too much. 

I can make a new issue for actually incorporating and sending the droppedColumns to the frontend.

**Review by d-callan — APPROVED** [review]

**Pull request merged**
